### ISSUE TITLE
连接优化建议

### ISSUE THREAD

**Issue by fcwys** [ffay/lanproxy#100]
服务器30m带宽，内网穿透后速度较慢，远程桌面和ssh等时有卡顿，希望能优化连接速度，也可以考虑对数据进行压缩传输，此外希望能开发Windows的gui客户端，支持开机自启和最小化托盘等，谢谢！

**Comment by ffay** [comment]
快慢还与你本地的宽带有关，一般本地的宽带上行速度都比较慢，比如电信开的100M带宽上行速度才几M

**Comment by fcwys** [comment]
已经测试过了，只是希望能有压缩减少数据传输

**Comment by fcwys** [comment]
可以考虑支持snappy压缩
