### ISSUE TITLE
用我的域名申请了letsencrypt的证书，设置cname记录，出现“使用了无效的安全证书”的问题

### ISSUE THREAD

**Issue by nmuxiang** [ffay/lanproxy#104]
用自己的域名申请了letsencrypt的证书，添加了cname的记录，但是访问的时候出现“您的连接并不安全”问题，请问该怎么弄？
![669661546](https://user-images.githubusercontent.com/18493976/51796947-70f20b80-2236-11e9-9561-5cee3b8ac265.png)

**Comment by WinteWu** [comment]
用nginx 设置好ssl，再跳转到代理端口

**Comment by nmuxiang** [comment]
自己弄了个主机，没用这种方法了，谢谢
