### ISSUE TITLE
下载地址被植入了html木马病毒，请删除一下html里面的病毒。

### ISSUE THREAD

**Issue by HaoQinLandv** [ffay/lanproxy#109]
下载地址被植入了html木马病毒，请手动删除一下html的病毒
https://seafile.io2c.com/d/2e81550ebdbd416c933f/?p=/

proxy-server-0.1.zip 

2019-01-29
--

--

**Comment by HaoQinLandv** [comment]
程序运行后，静态文件就插入了html病毒代码，属于网页挂马。请不要下载编译好的文件。

**Comment by ffay** [comment]
@HaoQinLandv 未发现异常，具体是哪个页面呢？
