### ISSUE TITLE
请问作者，lanproxy.io2c.com  是有替代的网址吗？

### ISSUE THREAD

**Issue by 172721404** [ffay/lanproxy#111]
在项目主页的简介出看到这个地址  https://lanproxy.io2c.com  但是不管是直接打开还是梯子都不能打开？请问此站点内是有相关的文档还是什么内容呢？

**Comment by ffay** [comment]
现在还打不开吗？再试试呢

**Comment by 172721404** [comment]
![image](https://user-images.githubusercontent.com/19380127/59584992-0a508a00-9112-11e9-9c22-9504a372de92.png)
不能打开，不管是梯子还是.....

**Comment by ffay** [comment]
dns被污染了，看来需要换域名了

**Comment by 172721404** [comment]
![image](https://user-images.githubusercontent.com/19380127/59586364-5b15b200-9115-11e9-862d-02c747edd2b3.png)
我用的梯子哦？照样打不开的哦

**Comment by ffay** [comment]
dns被乱指向了

**Comment by 172721404** [comment]
麻烦提供正确的服务器地址，我本地劫持吧

**Comment by ffay** [comment]
103.19.2.56

**Comment by 172721404** [comment]
![image](https://user-images.githubusercontent.com/19380127/59588135-81d5e780-9119-11e9-9fb3-d2cf8194dd63.png)
![image](https://user-images.githubusercontent.com/19380127/59588147-87333200-9119-11e9-9ee1-3fa3be0767b1.png)
本地劫持后还是打不开，用了梯子可以打开了但是怎么是Facebook的站点啊？

**Comment by ffay** [comment]
dns被改了，用这个吧
https://lan.io2c.com

**Comment by 172721404** [comment]
![image](https://user-images.githubusercontent.com/19380127/59589255-1c372a80-911c-11e9-8727-5438030518b9.png)
可以打开了 作者是否能跟新下项目上的地址呢？还是留着等有缘人来找到这篇wiki...

**Comment by ffay** [comment]
已更新

**Comment by 172721404** [comment]
完结 撒花
