### ISSUE TITLE
代理后的请求如何获取到请求发起端的ip

### ISSUE THREAD

**Issue by wenhaofan** [ffay/lanproxy#118]
经过代理后的请求通过request.getRemoteAddr()获取到的ip就都变成了127.0.0.1，有没有办法将该ip值修改为未代理前的请求ip,或者在header中添加Proxy-Client-IP之类的信息

**Comment by ffay** [comment]
由于是代理的tcp连接，并不知道什么协议，所以不不能增加header，如果要解决这个问题，可以这样
nginx -> lanproxy-server <--> lanproxy-client -> local-server
也就是在你公网服务器上增加一个nginx，nginx上可以配置
```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

**Comment by wenhaofan** [comment]
好的 谢谢
