### ISSUE TITLE
咨询版主

### ISSUE THREAD

**Issue by zhangxiaodong1209** [ffay/lanproxy#124]
初次使用，请教：
下载源码，执行mvn package 编译成功。
执行java -jar proxy-server\target\proxy-server-0.1.jar 后异常
将distribution下proxy-server-0.1和proxy-server-0.1.jar 放到tomcat中启动后，仍无法访问，请问这个java项目不是web项目么？
是哪些步骤有问题么？

**Comment by ffay** [comment]
编译完成后 直接运行bin目录下的 start和stop脚本即可
