### ISSUE TITLE
是否考虑重新设计一下Web管理的接口

### ISSUE THREAD

**Issue by towerhe** [ffay/lanproxy#14]
简单的看了一下现在的Web管理接口部分，基本上是通过JSON来进行数据交换的，是否考虑设计一套符合JSONAPI规范的接口呢？

`lanproxy`与我以前想的功能需求高度一致，非常感谢 @ffay 

非常有兴趣参与`lanproxy`的后期开发。

**Comment by ffay** [comment]
非常感谢对这个项目的关注，短期内没有重新设计web管理接口的计划，现在主要是在做一些稳定性的优化，如果有什么新的想法可以提出来。
