### ISSUE TITLE
使用内网IP可以访问，为什么使用公网IP就不行了？大神，你是怎么使用的？

### ISSUE THREAD

**Issue by yanghaojie002** [ffay/lanproxy#145]
使用IPconfig查出来的，内网IP是可以的：
![image](https://user-images.githubusercontent.com/34497376/83991042-2336f880-a97e-11ea-90be-9906553d830d.png)
![image](https://user-images.githubusercontent.com/34497376/83991051-2af69d00-a97e-11ea-8aef-702de17d2f97.png)

在https://www.ip138.com/ 这个网站查了一下对应的公网IP：
配置到server中的config.properties，
启动就报错了，请问大神，你是怎么设置，然后用起来的？
![image](https://user-images.githubusercontent.com/34497376/83991061-35189b80-a97e-11ea-976c-0ee7fe708327.png)
![image](https://user-images.githubusercontent.com/34497376/83991066-3b0e7c80-a97e-11ea-8716-d7ebe5c42ed3.png)

难道必须要买服务器，普通的台式机当不了服务器吗？

**Comment by ffay** [comment]
普通台式机没有独立的ip，不能直接被公网访问

**Comment by yanghaojie002** [comment]
> 普通台式机没有独立的ip，不能直接被公网访问

那应该怎么解决呢？
之前看到过有人在二手市场买了一台物理服务器，也是用这个项目，用一个公网的IP映射到本地，就成功了。
为什么他的公网IP就可以呢？
![image](https://user-images.githubusercontent.com/34497376/84461322-c057a100-ac9e-11ea-9bb5-6c9874799189.png)
