### ISSUE TITLE
web配置控制台 js无法加载

### ISSUE THREAD

**Issue by cfl520** [ffay/lanproxy#168]
org.fengfei.lanproxy.server.config.web.HttpRequestHandler类
  String url = request.getUri().replace(".", "");这里会替换掉uri中的“.”
  导致文件无法找到：
INFO [org.fengfei.lanproxy.server.config.web.HttpRequestHandler] - <not file::/home/proxy-server-0.1/webpages/jquery/jqueryi18npropertiesminjs>
INFO [org.fengfei.lanproxy.server.config.web.HttpRequestHandler] - <not file::/home/proxy-server-0.1/webpages/jquery/jquery-311minjs>
INFO [org.fengfei.lanproxy.server.config.web.HttpRequestHandler] - <not file::/home/proxy-server-0.1/webpages/jquery/jqueryi18npropertiesminjs>
INFO [org.fengfei.lanproxy.server.config.web.HttpRequestHandler] - <not file::/home/proxy-server-0.1/webpages/jquery/jqueryi18npropertiesminjs>
INFO [org.fengfei.lanproxy.server.config.web.HttpRequestHandler] - <not file::/home/proxy-server-0.1/webpages/jquery/jquery-311minjs>
INFO [org.fengfei.lanproxy.server.config.web.HttpRequestHandler] - <not file::/home/proxy-server-0.1/webpages/jquery/jqueryi18npropertiesminjs>

**Comment by ffay** [comment]
已修复。
