### ISSUE TITLE
是否考虑对proxy-server增加socks服务的支持呢

### ISSUE THREAD

**Issue by qfrank** [ffay/lanproxy#22]
@ffay 
形如`ssh -R xxxx:localhost:xxxx user@xxxx -p xxx -fTNC`的功能lanproxy已经做到了 ):
还缺个类似 `ssh -D localport user@proxy-server`

**Comment by Coneboy-k** [comment]
我觉得作者的lanproxy旨在做 TCP 协议的中转，如果增加应用层功能，会导致发展方向失控。我觉得后续的方向应该增加传输协议上的支持 比如 UDP 等。就好比路给你建好了，上面跑汽车、摩托车都行。

**Comment by lazy-luo** [comment]
socks服务一般都用现成的工具吧，直接代理出来就可以了。
@Coneboy-k 赞同。可以试试smarGate ，开车可以有多条路
