### ISSUE TITLE
建议调整空闲检测时间

### ISSUE THREAD

**Issue by Coneboy-k** [ffay/lanproxy#23]
@ffay 
我使用**lanproxy** 代理我的ss， 因为ss-server在美国，网络访问波动比较大。导致后续请求的block很严重。 相反我在使用国内服务器进行中转，速度很快。
 
![untitled](https://user-images.githubusercontent.com/3970260/31593427-323bf882-b1f4-11e7-8a1f-d654fc190d76.png)

我分析
有时候 lanproxy-client 会认为的链接断掉，然后关闭远程channel，然而我 ss-local 这边还以为链接存在，导致请求被hold住，后续的链接被block.

后面我把 **idle** 调整到60s，和 ss 的改成一样。后续查看日志，发现链接被block的情况少了很多。

lanproxy-client 请求消息转发这块，对于数据的转发，我理解是一个耗时操作，应该使用 queue 来处理，这样避免 **block** 后续的相同 **channel** 的数据收发。

**Comment by ffay** [comment]
数据转发这块做了流量控制，自动适配网络带宽，没有用队列防止过多的内存消耗

**Comment by Coneboy-k** [comment]
感谢@ffay 回复  我在lanproxy  ser-client 之间用kcptun 做了udp 加速。 效果好了很多。是否可以kcp协议的支持？  或者 可以提交 PR?  ;-)

**Comment by ffay** [comment]
最近正在研究kcp协议，有计划后续集成进去
