### ISSUE TITLE
idea启动时404

### ISSUE THREAD

**Issue by thanksGitHub** [ffay/lanproxy#30]
我把源码clone起来，运行server的测试用例，日志server.log显示正常，但请求ip+port报404.运行mvn package -Dmaven.test.skip 生成的包运行又可以。请问我该如何本地调试。麻烦作者有空的时候可以回答。

**Comment by ffay** [comment]
eclipse里面运行应该是没有问题的

下面是 org.fengfei.lanproxy.server.config.web.HttpRequestHandler 代码中读取页面路劲的代码，可以设置系统变量 app.home 
```java
private static final String PAGE_FOLDER = System.getProperty("app.home", System.getProperty("user.dir"))
            + "/webpages";
```

**Comment by thanksGitHub** [comment]
非常感谢作者，你的提醒让我关注PAGE_FOLDER的路径问题，我检查了一下，确实这里IDEA里面可能获取的路径不对，我加上子模块的路径后就可以成功。再次感谢作者及时的回复。希望后面我可以给提交一部分代码，丰富这个作品。
