### ISSUE TITLE
Ubuntu上无法正常启动server端和client端

### ISSUE THREAD

**Issue by ResolveWang** [ffay/lanproxy#31]
无法通过[release](https://github.com/ffay/lanproxy/releases)和文档成功运行landproxy。PID为空。

操作系统
> Ubuntu 16.04.1 (腾讯云) 64位

JDK版本
> openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

lanproxy版本
> v0.1-beta-1

如何复现
> wget https://github.com/ffay/lanproxy/archive/0.1-beta-1.tar.gz
> tar -zxvf 0.1-beta-1.tar.gz 
>cd lanproxy-0.1-beta-1/proxy-server/src/main/resources/
>sudo chmod 755 startup.sh
> ./startup.sh

出现错误
>  cannot access '/home/ubuntu/project/lanproxy-0.1-beta-1/proxy-server/src/main/lib': No such file or directory

然后通过
> mkdir -p /home/ubuntu/project/lanproxy-0.1-beta-1/proxy-server/src/main/lib
>  ./startup.sh

然后控制台的输出如下
> Starting the proxy server ...started
> PID: 

查看日志
> Error: Could not find or load main class org.fengfei.lanproxy.server.ProxyServerContainer

这是启动服务端的问题。然后我在自己的PC机(Ubuntu17)上启动客户端，也是这个现象，只有命令行输出，然后PID也是空。

想问一下，是我哪里操作出了问题吗？我主要不是写java的，所以想帮忙改进也无能为力。

---

不过有一点建议：可以再改改readme，把过程改具体一些，还有比如哪个文件位于哪个路径最好也贴一个链接，否则只有去一层层的找。

**Comment by thanksGitHub** [comment]
你是不是下错了啊，不是源码下载的文件只有几个吧bin，config，lib，webpages，logs。你不是Java开发没有必要走编译运行，所以我建议你检查一下是否下错了。

**Comment by ResolveWang** [comment]
@thanksGitHub 多谢提醒，我是下错了，我在releases中下的source code 而不是二进制文件。谢了哈

**Comment by ResolveWang** [comment]
感谢感谢，现在确实可以使用ssh到内网了，自己用腾讯云搭了一个服务端，感觉速度很快，比ngrok快多了。

感谢作者和楼上。
