### ISSUE TITLE
es集群内网穿透问题 是lanproxy的问题还是集群本身的问题

### ISSUE THREAD

**Issue by zhugw** [ffay/lanproxy#32]
在阿里云上的服务器部署了应用 需要访问局域网环境的es集群

```
192.168.0.21 9300
192.168.0.22 9300
192.168.0.25 9300
```
于是使用了lanproxy来进行内网穿透 以便通过外网地址来访问局域网的es服务

    120.27.XXX.XXX 9300 <--> 192.168.0.21 9300
    120.27.XXX.XXX 9200 <--> 192.168.0.21 9200
    
并且可以成功的通过如下的地址来查看集群状态

    http://120.27.XXX.XXX:9200/_cluster/health?pretty=

  
但是实际启动工程时发现 仍是连不上 通过抓包工具发现怎么连得还是局域网地址啊

<img width="913" alt="dingtalk20171108204708" src="https://user-images.githubusercontent.com/4953871/32551592-ae807e44-c456-11e7-9f51-d7c4d1372879.png">

但是我代码中明明使用的是外网地址啊

    .addServerAddress("120.27.XXX.XXX", 9300)

**Comment by ffay** [comment]
lanproxy和es都没问题
只是因为客户端作为节点加入es集群通过这种代理方式有问题，es集群模式相互连接通信需要在相同的局域网里面，如果只是访问es的http接口是没有问题的

**Comment by zhugw** [comment]
谢谢！ 那有破解的方法吗？

**Comment by ffay** [comment]
使用 transport-client，把探测集群节点功能 client.transport.sniff 设置为false试试
 https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/transport-client.html
