### ISSUE TITLE
linux下客户端如何做成systemctl服务呢？

### ISSUE THREAD

**Issue by jyy1082** [ffay/lanproxy#61]
想把客户端做成systemctl服务开机自动运行，但是尝试很多次没有成功，服务脚本如下：

[Unit]
Description=lanproxy tunnel
After=network.target
[Service]
Type=forking
ExecStart=/home/pi/client_linux_arm7 -s 192.168.1.175 -p 4900 -k bce8b06504ad44938cfb5989a7c19c2c
User=root
Group=root
[Install]
WantedBy=multi-user.target

请问ExecStart后面的命令改如何写呢？谢谢！

**Comment by ffay** [comment]
就是你现在这样写的吧

**Comment by jyy1082** [comment]
服务启动，还是遇到关闭窗口服务停了
