### ISSUE TITLE
请问如何调整代码使得client能连接到负载均衡后面特定的服务器

### ISSUE THREAD

**Issue by bejondshao** [ffay/lanproxy#68]
我有一个局域网， 部署了client， 有一个负载均衡，后面如果有一个内网的服务器（server所在的机器）。client配置的host是负载均衡的主机地址， 可以连接到server。 问题是如果内网服务器有两个server， 而server使用的同一套配置文件（我持久化到数据库了）， 如何让client分别创建两个连接连到这两个server上？

**Comment by ffay** [comment]
最简单的方法运行两个客户端，各连一台server

**Comment by maicos520** [comment]
客户端的配置文件在~/.lanproxy目录下，所以不能直接开两个server端，但我是用docker部署的两个server做负载的

**Comment by bejondshao** [comment]
@maicos520 谢谢
