### ISSUE TITLE
RTSP代理好像不行

### ISSUE THREAD

**Issue by sbtdkj1017** [ffay/lanproxy#80]
尝试把摄像头代理到外网，发现播放不了。是不是对rtsp协议不支持？虽然也是TCP的
但试了http服务是可以的正常代理的

**Comment by mingio** [comment]
我试过，基于tcp的rtsp可以播放

**Comment by sbtdkj1017** [comment]
不是代理的问题，是有依赖UDP导致，改成全TCP就可以用
